pipeline {
    agent {
    stages {
        stage('Build') {
            steps {
            	bat 'e:'
            	bat 'cd E:\1723080446\simple-java-maven-app'
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
